name: Build OpenCV Python Wheels

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version: ["3.11", "3.12"]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install --quiet -y --no-install-recommends \
          gstreamer1.0-gl \
          gstreamer1.0-opencv \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-tools \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer1.0-0 \
          libgstreamer1.0-dev

    - name: Run build script
      env:
        OPENCV_VER: "84"
        ENABLE_CONTRIB: "0"
        ENABLE_HEADLESS: "1"
        CMAKE_ARGS: "-DWITH_GSTREAMER=ON"
      run: |
        cd /tmp
        git clone --branch ${OPENCV_VER} --depth 1 --recurse-submodules --shallow-submodules https://github.com/opencv/opencv-python.git opencv-python-${OPENCV_VER}
        cd opencv-python-${OPENCV_VER}
        cp /home/runner/work/pyfiles/pyfiles/pyproject.toml .
        python -m pip wheel . --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: opencv_wheel_${{ matrix.os }}_py${{ matrix.python-version }}
        path: /tmp/opencv-python-*/*.whl
