name: Build OpenCV Wheel

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        architecture: ["x64", "arm64"]
        include:
          - python-version: "3.11"
            os: ubuntu-22.04
          - python-version: "3.12"
            os: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install --quiet --no-install-recommends -y build-essential cmake git \
              gstreamer1.0-gl \
              gstreamer1.0-opencv \
              gstreamer1.0-plugins-bad \
              gstreamer1.0-plugins-good \
              gstreamer1.0-plugins-ugly \
              gstreamer1.0-tools \
              libgstreamer-plugins-base1.0-dev \
              libgstreamer1.0-0 \
              libgstreamer1.0-dev

    - name: Build OpenCV wheel
      env:
        OPENCV_VER: "82"
        ENABLE_CONTRIB: "0"
        ENABLE_HEADLESS: "1"
        CMAKE_ARGS: "-DWITH_GSTREAMER=ON"
      run: |
        TMPDIR=$(mktemp -d)
        cd "${TMPDIR}"
        git clone --branch ${OPENCV_VER} --depth 1 --recurse-submodules --shallow-submodules https://github.com/opencv/opencv-python.git opencv-python-${OPENCV_VER}
        cd opencv-python-${OPENCV_VER}

        # Remove the "setuptools==59.2.0" line from pyproject.toml
        sed -i '/"setuptools==59.2.0",/d' pyproject.toml

        python -m pip wheel . --verbose

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: opencv-wheels-${{ matrix.architecture }}-${{ matrix.python-version }}
        path: "${{ runner.temp }}/**/*.whl"
